---
- name: "Add users"
  hosts: 192.168.1.34
  become: yes
  remote_user: nvs0003

  tasks:
    - name: Add a user
      user:
        name: ansibleuser
        comment: Anisble User
        uid: 1234
        group: sudo
