---
- name: "check for updates"
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: root
  
  tasks:
  - name: chcekcs for updates
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: true
